export * as UserController from "./UserController.js";
export * as PostController from "./PostController.js";
export * as ServiceController from "./ServiceController.js";
export * as OnlineRehabilitationController from "./OnlineRehabilitationController.js";
export * as TrainingController from "./TrainingController.js";
export * as CustomerController from "./CustomerController.js";
export * as AppointmentController from "./AppointmentController.js";
export * as EmployerController from "./EmployerController.js";
export * as WorkTimeController from "./WorkTimeController.js";